import sys
import numpy as np
import qimage2ndarray
from PIL import Image
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox.setGeometry(QtCore.QRect(10, 60, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ComboBox.setFont(font)
        self.ComboBox.setObjectName("ComboBox")
        self.ComboBox.addItems(['камера № 1', 'камера № 2', 'камера № 3'])
        self.ComboBox.setCurrentText('')
        self.LabelCameraChoose = QtWidgets.QLabel(self.centralwidget)
        self.LabelCameraChoose.setGeometry(QtCore.QRect(70, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelCameraChoose.setFont(font)
        self.LabelCameraChoose.setObjectName("LabelCameraChoose")
        self.PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton.setGeometry(QtCore.QRect(10, 110, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PushButton.setFont(font)
        self.PushButton.setObjectName("PushButton")
        self.LabelCameraVideo = QtWidgets.QLabel(self.centralwidget)
        self.LabelCameraVideo.setGeometry(QtCore.QRect(306, 22, 431, 261))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelCameraVideo.setFont(font)
        self.LabelCameraVideo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LabelCameraVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCameraVideo.setObjectName("LabelCameraVideo")
        self.LabelCameraVideo.setStyleSheet("border: 1px solid black;")
        self.LabelPlateNumberFrame = QtWidgets.QLabel(self.centralwidget)
        self.LabelPlateNumberFrame.setGeometry(QtCore.QRect(306, 300, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelPlateNumberFrame.setFont(font)
        self.LabelPlateNumberFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelPlateNumberFrame.setObjectName("LabelPlateNumberFrame")
        self.LabelPlateNumberFrame.setStyleSheet("border: 1px solid black;")
        self.TableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.TableWidget.setGeometry(QtCore.QRect(10, 160, 271, 201))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(2)
        self.TableWidget.setRowCount(0)
        self.TableWidget.setHorizontalHeaderLabels(['Номерной знак', 'Результат'])
        self.LabelTraficLights = QtWidgets.QLabel(self.centralwidget)
        self.LabelTraficLights.setGeometry(QtCore.QRect(550, 300, 189, 61))
        self.LabelTraficLights.setText("")
        self.LabelTraficLights.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelTraficLights.setObjectName("LabelTraficLights")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vehicle access control complex"))
        self.LabelCameraChoose.setText(_translate("MainWindow", "Выберите камеру"))
        self.PushButton.setText(_translate("MainWindow", "Взаимодействие с БД"))
        self.LabelCameraVideo.setText(_translate("MainWindow", "Камера не выбрана"))
        self.LabelPlateNumberFrame.setText(_translate("MainWindow", "Номеров не обнаружено"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
